entryPoints:
  web:
    address: ':80'
    http:
      aliasHeadersStrategy: reject
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'
    http:
      aliasHeadersStrategy: reject
providers:
  file:
    directory: /var/lib/paas-routes
    watch: true
api:
  dashboard: false
log:
  level: INFO
global:
  checkNewVersion: false
  sendAnonymousUsage: false
